name: DevSync Automated Daily Commit

on:
  schedule:
    - cron: '30 6 * * *'  # Runs daily at 6:30 AM UTC (Adjust as needed)
  workflow_dispatch:  # Allows manual triggering

jobs:
  daily-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add a commit with your email 24f1000313@ds.study.iitm.ac.in
        run: |
          echo "Automated daily commit on $(date)" >> daily-log.txt
          git config --global user.name "GitHub Actions"
          git config --global user.email "24f1000313@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Automated daily commit by GitHub Actions"
          git push
