name: Daily Commit

on:
  schedule:
    - cron: '58 12 9 2 0'  # Runs at 12:58 UTC on February 9th (Sunday)
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  create-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create empty commit (24f1000313@ds.study.iitm.ac.in)
        run: |
          git config --local user.email "24f1000313@ds.study.iitm.ac.in"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Daily commit"
          git push
